### ISSUE TITLE
Renomear obtenção-senado

### ISSUE THREAD

**Issue by docardoso** [docardoso/analisepolitica#1]
Renomear script de obtenção do senado para obtencao_dados.py, considerando que ele será o ponto de partida parao script geral para popular o BD.  

_Sent from my Motorola MotoG3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gabe-nasc** [comment]
Resolvido no commit [622a553](https://github.com/docardoso/analisepolitica/commit/622a553a9bbeafc6e7a97377e3cf746d9fb4eb01)
