### ISSUE TITLE
Popular BD com todos os senadores

### ISSUE THREAD

**Issue by docardoso** [docardoso/analisepolitica#2]
Inserir na tabela Parlamentares registros relativoa a todos os senadores que participaram de votações em 2017.

_Sent from my Motorola MotoG3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gabe-nasc** [comment]
Resolvido no commit [622a553](https://github.com/docardoso/analisepolitica/commit/622a553a9bbeafc6e7a97377e3cf746d9fb4eb01)
