### ISSUE TITLE
Retificação da chave da tabela Parlamentar

### ISSUE THREAD

**Issue by docardoso** [docardoso/analisepolitica#5]
Considerando que os ids dos parlamentares serão os mesmos obtidos dos dados públicos, há chance de coincidências. Por conta disto, utilizar o par id-casa como chave da tabela Parlamentar.

_Sent from my Motorola MotoG3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gui-lourenco** [comment]
Chave da tabela retificada 

_Sent from my Samsung SM-J320M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
