### ISSUE TITLE
Adição de ids próprios nas tabelas Parlamentar e Votação

### ISSUE THREAD

**Issue by docardoso** [docardoso/analisepolitica#8]
Alterar as tabelas citadas para que tenham como chave primária um id gerado automaticamente (autoincremento), além de terem um atributo adicional (id_api) cujo valor é o id original das API web.

**Comment by gui-lourenco** [comment]
adicionado no commit (eb9b646)

**Comment by gui-lourenco** [comment]
alteração feita no (commit d88239950b5b8f31a11c7720b39035861ab1103a )
